# -*- coding: utf-8 -*-
"""Homework9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vIl3JOm78Zeo8fBkOUL-WqiewnHRvBcn
"""

import pandas as pd
df = pd.read_csv("/content/sample_data/california_housing_train.csv")

df

df[(df["population"]>0) & 
   (df["population"]<500)]["median_house_value"].describe()

df[df["population"]==df["population"].min()]["households"].max()